version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-prisma}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-prisma}
      POSTGRES_DB: ${DB_NAME:-gestion_test}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-prisma} -d ${DB_NAME:-gestion_test}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://${DB_USER:-prisma}:${DB_PASSWORD:-prisma}@postgres:5432/${DB_NAME:-gestion_test}
      NEXTAUTH_URL: http://localhost:4000
      NEXTAUTH_SECRET: dev_secret
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/app
    command: sh -c "npx prisma generate && NODE_ENV=development npx tsx server.ts"

volumes:
  postgres_data: {}
  redis_data: {}
